 numpy

 ### импортируем библиотеку numpy

In [1]:
import numpy as np #импорт библиотеки 

In [2]:
np.random.seed(42) #установка номера файла с псевдослучайными числами

In [7]:
np.random.randint(5,10) #генерация случайного числа в пределах от 5 до 10, третьим параметром можно указать шаг

9

In [8]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])

# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

### 

In [11]:
a2 #просмотр списков

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [12]:
a2.shape #форма списка

(2, 3)

In [13]:
a2.ndim #количество размерности, понять сколько размерности: вектор, 2мерная матрица или 3х мерная матрица, n-матрица 

2

In [14]:
a3.ndim

3

In [15]:
a2.dtype #тип данных, который хранится внутри списка

dtype('float64')

In [16]:
a2.size #размер, количество элементов. как в списке задач


6

In [17]:
a3.size

18

In [18]:
type(a2) # что такое сам список, тип данных

numpy.ndarray

# создание списков

In [19]:
simple_array = np.array([1,2,3]) #простейший список 

In [20]:
second_array = np.array([[0,0,],
                       [1, 1]]) # простейшая матрица

In [21]:
second_array

array([[0, 0],
       [1, 1]])

In [22]:
second_array.shape #форма списка

(2, 2)

In [23]:
second_array.dtype #тип 


dtype('int64')

In [24]:
ones=np.ones((10, 2)) #создание списка из единиц

In [25]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
zeros=np.zeros((2, 3)) #тоже самое только из нолей

In [27]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array = np.arange(1, 10, 2) #создание списка от 1 до 10 с шагом 2

In [29]:
range_array

array([1, 3, 5, 7, 9])

In [32]:
random_array=np.random.randint(10, size = (2, 3))

In [33]:
random_array

array([[6, 7, 4],
       [3, 7, 7]])

In [34]:
np.random.random((5, 3)) #список чисел от 1 до 10 размер списка 5 на 3, сама функция генерирует числа от 1 до 10 

array([[6.50888473e-01, 5.64115790e-02, 7.21998772e-01],
       [9.38552709e-01, 7.78765841e-04, 9.92211559e-01],
       [6.17481510e-01, 6.11653160e-01, 7.06630522e-03],
       [2.30624250e-02, 5.24774660e-01, 3.99860972e-01],
       [4.66656632e-02, 9.73755519e-01, 2.32771340e-01]])

In [35]:
np.random.rand(5, 3) #здесь функция генерирует чила от 0 до 1

array([[0.09060643, 0.61838601, 0.38246199],
       [0.98323089, 0.46676289, 0.85994041],
       [0.68030754, 0.45049925, 0.01326496],
       [0.94220176, 0.56328822, 0.3854165 ],
       [0.01596625, 0.23089383, 0.24102547]])

### сравнение и манипуляции со списками

In [36]:
a1

array([1, 2, 3])

In [37]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
ones=np.ones(3)

In [39]:
ones


array([1., 1., 1.])

In [40]:
a1+ones #сложение списков

array([2., 3., 4.])

In [41]:
a1-ones #вычетание

array([0., 1., 2.])

In [42]:
a1*ones

array([1., 2., 3.])

In [43]:
a1/ones

array([1., 2., 3.])

In [44]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

мы можем производить арифметические операции над списками и числами, числами и числами, списками и списками.

In [47]:
np.min(a2) #минимальное значение списка

1.0

In [48]:
np.max(a2) #максимальное значение 

6.5

In [49]:
np.mean(a2) #среднее значение спсика

3.6333333333333333

In [50]:
np.std(a2) #стандартное отклонение

1.8226964152656422

In [51]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [52]:
a2.shape

(2, 3)

In [98]:
a2+a3

array([[[ 2. ,  3. ,  4. ],
        [ 6. ,  7. ,  8. ],
        [10.3, 11.3, 12.3]],

       [[14. , 15. , 16. ],
        [18. , 19. , 20. ],
        [22.5, 23.5, 24.5]]])

In [55]:
a2 = a2.reshape(2, 3, 1) #смена формы списка 

In [56]:
a2+a3

array([[[ 2. ,  3. ,  4. ],
        [ 6. ,  7. ,  8. ],
        [10.3, 11.3, 12.3]],

       [[14. , 15. , 16. ],
        [18. , 19. , 20. ],
        [22.5, 23.5, 24.5]]])

In [57]:
a2

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [58]:
a2.T #транспонирование,- меняем местами столбцы и строки

array([[[1. , 4. ],
        [2. , 5. ],
        [3.3, 6.5]]])

In [59]:
mat1 = np.random.randint(10, size=(3, 3)) #создание списка псевдослучайных чисел от 0 до 10 размером 3 на 3
mat2 = np.random.randint(10, size=(3, 2))

In [61]:
np.dot(mat1, mat2) #преумноужение матриц

array([[103,  53],
       [ 32,  10],
       [ 67,  45]])

In [62]:
a1>a2 #сравнение элементов матрица

array([[[False,  True,  True],
        [False, False,  True],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]]])

In [63]:
a1>=a2

array([[[ True,  True,  True],
        [False,  True,  True],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]]])

In [64]:
a1==a3


array([[[ True,  True,  True],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]]])

In [65]:
random_array

array([[6, 7, 4],
       [3, 7, 7]])

In [66]:
np.sort(random_array)

array([[4, 6, 7],
       [3, 7, 7]])

In [67]:
zeros=np.zeros(6)

In [68]:
zeros


array([0., 0., 0., 0., 0., 0.])

In [69]:
zeros=np.zeros(11)

In [70]:
zeros[6]=11

In [71]:
zeros


array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

In [72]:
i=np.random.randint(13,38)

In [75]:
i

24

In [77]:
i=np.arange(13, 38)

In [78]:
i

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33, 34, 35, 36, 37])

In [79]:
i=i.astype(str)

In [80]:
i

array(['13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34',
       '35', '36', '37'], dtype='<U21')

In [81]:
a=np.ones(5)

In [85]:
a=np.append(a,0)

In [88]:
a=np.insert(a, 0, 0)

In [95]:
a=np.random.randint(0, 10, size=5)
b=np.random.randint(0, 10, size=5)
for i in a:
    if i in b:
        print(i)

7
6


In [96]:
np.sort(a)

array([0, 1, 6, 7, 8])